# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab7929e14c8d0f223773cfbfda4054ce6828286c1d8bcffa2adb3a9e660eccc80a30c00cba2a440829365e6bab21b9a293d60c931e6dd9eb23b8ab75f574b1e6

test:
  secret_key_base: 2ac0e4e4b63c1a6aae7685e170293534cbc3f937956363ab1740d8cdcd711b0a7558b3268948c0430957939cfbaae10c46322357f0b025e53786daae04ccc2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
