Idea.create(title: "hello", body: "this is pretty cool")
Idea.create(title: "hi", body: "you are cool")
Idea.create(title: "whoa", body: "life is awesome")
Idea.create(title: "neat", body: "I love everyone")
Idea.create(title: "haiii", body: "I am the best")
