Idea.create(title: "hello", body: "this is pretty cool")
Idea.create(title: "hi", body: "you are cool")
Idea.create(title: "whoa", body: "life is awesome")
Idea.create(title: "neat", body: "I love everyone")
Idea.create(title: "haiii", body: "this is pretty cool and I do believe that I will live forever and have a wonderful unicorn to ride everyday and her name is Sasha")
